#!/usr/bin/env bash
# generate-build-info.sh
#
# Pre-build script (xcodegen `preBuildScripts`) that stamps
# `Generated/BuildInfo.swift` with the current MARKETING_VERSION,
# CURRENT_PROJECT_VERSION (build number), git SHA, commit date,
# and dirty-tree flag.
#
# Idempotent: only writes when content changes, so Xcode's
# incremental build skips recompiles when nothing about the
# version changed.
#
# Inputs:
#   $MARKETING_VERSION       (Xcode-passed; else computed from VERSION)
#   $CURRENT_PROJECT_VERSION (Xcode-passed; else git rev-list --count HEAD)
#   $SRCROOT                 (Xcode-passed; else script-relative)
#
# Outputs:
#   ${SRCROOT}/VibeDashboard/Generated/BuildInfo.swift
#
# Modes:
#   (no args)          write Generated/BuildInfo.swift (the pre-build path).
#   --print-marketing  print the computed MARKETING_VERSION and exit — the
#                      Makefile reads this to stamp the shipped app bundle so
#                      CFBundleShortVersionString matches BuildInfo.

set -euo pipefail

# Resolve project root.
SRC="${SRCROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$SRC"

# MARKETING_VERSION from VERSION file (MAJOR + MINOR_BASE + commits-since-VERSION).
if [[ -f VERSION ]]; then
    VERSION_MAJOR=$(awk -F= '/^MAJOR=/ {print $2}' VERSION | tr -d ' ')
    VERSION_MINOR_BASE=$(awk -F= '/^MINOR_BASE=/ {print $2}' VERSION | tr -d ' ')
    if git rev-parse --git-dir >/dev/null 2>&1; then
        VERSION_COMMIT=$(git log -1 --format=%H -- VERSION 2>/dev/null || true)
        if [[ -n "$VERSION_COMMIT" ]]; then
            MINOR_DELTA=$(git rev-list --count "${VERSION_COMMIT}..HEAD" 2>/dev/null || echo 0)
        else
            MINOR_DELTA=0
        fi
    else
        MINOR_DELTA=0
    fi
    MARKETING="${VERSION_MAJOR}.$(( VERSION_MINOR_BASE + MINOR_DELTA ))"
else
    MARKETING="${MARKETING_VERSION:-1.0}"
fi

# --print-marketing: emit the computed version and stop. The Makefile calls
# this so the shipped CFBundleShortVersionString equals BuildInfo's version.
if [[ "${1:-}" == "--print-marketing" ]]; then
    printf '%s\n' "$MARKETING"
    exit 0
fi

# Build number from env (Xcode/Make pass it) or git.
BUILD_NUM="${CURRENT_PROJECT_VERSION:-}"
if [[ -z "$BUILD_NUM" ]] || [[ "$BUILD_NUM" == "1" ]]; then
    BUILD_NUM=$(git rev-list --count HEAD 2>/dev/null || echo 1)
fi

# Git metadata.
if git rev-parse --git-dir >/dev/null 2>&1; then
    SHA_SHORT=$(git rev-parse --short HEAD)
    SHA_FULL=$(git rev-parse HEAD)
    COMMIT_DATE=$(git log -1 --format=%cI)
    COMMIT_DATE_SHORT=$(git log -1 --format=%cs)
    if git diff-index --quiet HEAD -- 2>/dev/null; then
        IS_DIRTY="false"
        DIRTY_SUFFIX=""
    else
        IS_DIRTY="true"
        DIRTY_SUFFIX="+dirty"
    fi
else
    SHA_SHORT="unknown"; SHA_FULL="unknown"
    COMMIT_DATE="unknown"; COMMIT_DATE_SHORT="unknown"
    IS_DIRTY="false"; DIRTY_SUFFIX=""
fi

BUILD_DATE_ISO=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Find the main app source directory. Convention: the directory next
# to project.yml with the matching app name (`VibeDashboard/`). Override
# with $BUILDINFO_APP_DIR if your layout differs.
APP_DIR="${BUILDINFO_APP_DIR:-VibeDashboard}"
OUT_DIR="$SRC/$APP_DIR/Generated"
OUT_FILE="$OUT_DIR/BuildInfo.swift"
mkdir -p "$OUT_DIR"

NEW_CONTENT=$(cat <<EOF
// swiftlint:disable all
// AUTO-GENERATED by Scripts/generate-build-info.sh — DO NOT EDIT BY HAND.
import Foundation

/// Compile-time build metadata, captured by the pre-build script.
public enum BuildInfo: Sendable {
    public static let marketingVersion = "${MARKETING}"
    public static let buildNumber       = "${BUILD_NUM}"
    public static let commitShortSHA    = "${SHA_SHORT}${DIRTY_SUFFIX}"
    public static let commitFullSHA     = "${SHA_FULL}"
    public static let commitDateISO     = "${COMMIT_DATE}"
    public static let commitDateShort   = "${COMMIT_DATE_SHORT}"
    public static let buildDateISO      = "${BUILD_DATE_ISO}"
    public static let isDirty: Bool     = ${IS_DIRTY}

    /// Compact one-line label suitable for an About-screen footer.
    public static var compactLabel: String {
        "v\\(marketingVersion) (\\(buildNumber)) · \\(commitShortSHA) · \\(commitDateShort)"
    }
}
EOF
)

# Idempotency.
if [[ -f "$OUT_FILE" ]]; then
    EXISTING=$(cat "$OUT_FILE")
    if [[ "$EXISTING" == "$NEW_CONTENT" ]]; then
        echo "BuildInfo.swift unchanged (skip write)"
        exit 0
    fi
fi

printf '%s\n' "$NEW_CONTENT" > "$OUT_FILE"
echo "Wrote $OUT_FILE (v${MARKETING} build ${BUILD_NUM} sha=${SHA_SHORT}${DIRTY_SUFFIX})"
